title: "Home"
subtitle: "Homer"
logo: "logo.png"

stylesheet:
  - "assets/styles/home.css"
  - "assets/styles/nav.css"

header: false
footer: false

theme: default

colors:
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background-image: "../assets/themes/HudsonRiverValley/Background.png"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

links:
  - icon: "fas fa-house"
    url: "/" 
  - icon: "fas fa-file-alt"
    url: "#additional-page" 